# Generated by Django 4.2.1 on 2023-06-02 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 17, 30, 44, 748635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
